name = "vpn-api"
main = "src/index.ts"
workers_dev = false
compatibility_date = "2023-03-07"
usage_model= "unbound"

[vars]
DATA_API_URL = "https://eu-central-1.aws.data.mongodb-api.com/app/data-pfewh/endpoint/data/v1"

# The necessary secrets are:
# - DATA_API_KEY
